[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0xe9fe5fb0f8b24c09dc9526f4c030b49179598bc4de9e302943f2ca581137880e'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]